In [1]:
import numpy

In [3]:
flat_array = numpy.arange(1,10,0.5)
flat_array

array([ 1. ,  1.5,  2. ,  2.5,  3. ,  3.5,  4. ,  4.5,  5. ,  5.5,  6. ,
        6.5,  7. ,  7.5,  8. ,  8.5,  9. ,  9.5])

In [4]:
flat_array.ptp()

8.5

In [5]:
flat_array.mean(5)

5.25

In [6]:
flat_array.sum()

94.5

In [7]:
numpy.median(flat_array)

5.25

In [17]:
one_dim = numpy.array([1,2,3,4,5,10])
one_dim

array([ 1,  2,  3,  4,  5, 10])

In [19]:
two_dim = numpy.array([
    [1,2,3],
    [2,3,4],
    [3,4,10]])
    
two_dim

array([[ 1,  2,  3],
       [ 2,  3,  4],
       [ 3,  4, 10]])

In [20]:
two_dim[2]

array([ 3,  4, 10])

In [21]:
two_dim[2][1]

4

In [22]:
two_dim[2,1]

4

In [23]:
dir(two_dim)

['T',
 '__abs__',
 '__add__',
 '__and__',
 '__array__',
 '__array_finalize__',
 '__array_interface__',
 '__array_prepare__',
 '__array_priority__',
 '__array_struct__',
 '__array_wrap__',
 '__class__',
 '__contains__',
 '__copy__',
 '__deepcopy__',
 '__delattr__',
 '__delitem__',
 '__delslice__',
 '__div__',
 '__divmod__',
 '__doc__',
 '__eq__',
 '__float__',
 '__floordiv__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getitem__',
 '__getslice__',
 '__gt__',
 '__hash__',
 '__hex__',
 '__iadd__',
 '__iand__',
 '__idiv__',
 '__ifloordiv__',
 '__ilshift__',
 '__imod__',
 '__imul__',
 '__index__',
 '__init__',
 '__int__',
 '__invert__',
 '__ior__',
 '__ipow__',
 '__irshift__',
 '__isub__',
 '__iter__',
 '__itruediv__',
 '__ixor__',
 '__le__',
 '__len__',
 '__long__',
 '__lshift__',
 '__lt__',
 '__mod__',
 '__mul__',
 '__ne__',
 '__neg__',
 '__new__',
 '__nonzero__',
 '__oct__',
 '__or__',
 '__pos__',
 '__pow__',
 '__radd__',
 '__rand__',
 '__rdiv__',
 '__rdivmod__',
 '__reduce__',
 

In [24]:
one_dim + 2

array([ 3,  4,  5,  6,  7, 12])

In [25]:
plus_two = one_dim + 2

In [26]:
plus_two + one_dim

array([ 4,  6,  8, 10, 12, 22])

In [27]:
one_dim * 3

array([ 3,  6,  9, 12, 15, 30])

In [28]:
one_dim * plus_two

array([  3,   8,  15,  24,  35, 120])

In [29]:
(one_dim * plus_two).sum()

205

In [30]:
one_dim.dot(plus_two)

205

In [33]:
one_mill = numpy.random.randint(0,1000,100000)
one_mill

array([953, 353, 320, ...,  33, 418, 361])

In [34]:
one_mill.shape

(100000,)

In [35]:
one_mill * 2

array([1906,  706,  640, ...,   66,  836,  722])

Compare speed: numpy vs. regular python list

In [36]:
one_mill = list(one_mill)

In [41]:
new_list = []
for i in range(len(one_mill)):
    new_list.append(one_mill[i]*2)
new_list

[1906,
 706,
 640,
 1842,
 1332,
 188,
 1736,
 328,
 760,
 1254,
 1640,
 248,
 1744,
 592,
 970,
 1702,
 0,
 1746,
 1142,
 1726,
 1788,
 910,
 1894,
 1740,
 1336,
 1882,
 24,
 376,
 1070,
 1812,
 970,
 1452,
 560,
 822,
 1622,
 668,
 1012,
 1660,
 1514,
 484,
 1926,
 674,
 1408,
 1690,
 108,
 1052,
 1464,
 558,
 1460,
 1806,
 1704,
 994,
 472,
 1506,
 1878,
 586,
 1388,
 1032,
 940,
 496,
 600,
 1524,
 1248,
 286,
 646,
 610,
 1056,
 1632,
 902,
 1302,
 22,
 1142,
 964,
 1606,
 1934,
 6,
 1466,
 746,
 1392,
 1062,
 178,
 724,
 1822,
 378,
 90,
 1990,
 1776,
 1758,
 934,
 1338,
 1026,
 1930,
 750,
 176,
 496,
 782,
 752,
 1302,
 1918,
 82,
 346,
 944,
 566,
 1070,
 30,
 1710,
 1810,
 1024,
 588,
 1892,
 392,
 1118,
 10,
 906,
 1968,
 1264,
 512,
 1832,
 1900,
 1586,
 914,
 1906,
 808,
 1858,
 374,
 1002,
 448,
 1180,
 830,
 1648,
 1430,
 634,
 292,
 196,
 1142,
 34,
 1672,
 20,
 674,
 1574,
 1832,
 1316,
 586,
 1576,
 830,
 1316,
 1636,
 748,
 1480,
 1320,
 1394,
 1324,
 1220,
 680,
 78